### PR TITLE
Add Pricing Data

### PR DESCRIPTION
**Pull request by leesoh**
Hiya! Great port of CatMyFish. This PR adds the ability to pull pricing data from Gandi.net using the -p optional parameter. A free API key is required from: https://v4.gandi.net/admin/api_key. 

I also added a version requirement for lxml as I was getting irritating errors after upgrading to 3.8.

### CODE REVIEW

**Comment by andrewchiles** [comment]
Thanks for this PR. We'll check it out shortly!

**Comment by vestjoe** [comment]
I like this idea,  recently updated to include the Status column.  Price is somewhat shown here.  Available typically means standard price for that TLD.  Or a $ amount may be shown.  Either way, it is a quick indicator of price.

I like the clean up and fix to the requirements doc.  

The API requirement is the only thing I see as an issue.

I see the price check code is part of the reputation check.  I most often run this without reputation check (much faster) and manually check for domains I'm interested in.  If we added a dedicated price check, may need to move into its own optional section.
Thoughts?

**Comment by leesoh** [comment]
Yeah - I spent a (very small) bit of time looking for an API-less option but then decided it would be a fun excuse to build something. I understand completely if you a) want to drop it completely or b) are more interested in API-less options.

Regarding its location in code, I was trying not to modify your base code to much and added it under reputation since I figured your main goal here is looking for domains with a pre-existing reputation rather than just any recently expired domain with a given keyword. Can be moved wherever - I just stuck it there since it fit well.

**Comment by vestjoe** [comment]
I like a lot of the ideas.  If we move the pricing as an option with the API key as the parameter, maybe this will work.  I would rather not have to modify the code to add the api.  As for usage, I have the reputation search, but personally don't use right away.  We have had this tool (or a variation) for a couple of years now.  It works with the flow that we use.

I'd like an opinion on the status column.  It somewhat covers price.  What are your thoughts?  Is it helpful to have more detail?

I can update the code with your change ideas (include a reference to your contributions) or you can rework if you want to directly contribute the pull request.   I'm good either way.  You have some good ideas.

**Comment by leesoh** [comment]
I added the price specifically since I ran into a few domains that were available, but at ~$7600 or so (-q health). I'm all for moving the API key to the parameter and will do so tonight if you'd like to keep the feature. 

I'll get the API key moved to a parameter tonight and update the PR.

Regarding categorization, this dropped the other day: https://github.com/mdsecactivebreach/Chameleon. I feel a bit sheepish for not realizing how easy it is to categorize a domain and given this new information am not sure whether an expired domain being already categorized is of any benefit whatsoever.

**Comment by leesoh** [comment]
There's a dependency in parameters here (-p requires -c), but I left it as a documented requirement rather than trying to enforce it in case -p gets broken out into its own thing.

**Comment by vestjoe** [comment]
I haven't seen Chameleon... If it works, you are right, this tool may not be as helpful

I will take a look at your updates.

**Comment by andrewchiles** [comment]
Hey Liam, thanks again for taking a look at DomainHunter. We decided to hold off on merging the pricing API at this point. Ultimately if we add this feature, we'll prefer a solution that doesn't require a pre-existing account or at least doesn't require it to be pre-funded (as is the case with Gandi).

Thanks again!

**Pull request closed without merging**
